export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const POST_PREREG_DETAILS = "POST_PREREG_DETAILS";
export const REG_AUTH_CHECKER = "REG_AUTH_CHECKER";
export const REGISTER_USER = "REGISTER_USER";

export const GET_USER_PERIODS = "GET_USER_PERIODS";
export const GET_USER_TRANSACTION = "GET_USER_TRANSACTION";
export const POST_TRANSACTION = "POST_TRANSACTION";
export const FINANCE_VISUALIZER = "FINANCE_VISUALIZER";

export const SEND_MONEY_PRE_VERIFY = "SEND_MONEY_PRE_VERIFY";
export const POST_SEND_MONEY = "POST_SEND_MONEY";

export const GET_BANK = "GET_BANK";
export const RESOLVE_BANK = "RESOLVE_BANK";
export const UPDATE_BANK = "UPDATE_BANK";
export const WITHDRAW_TO_BANK = "WITHDRAW_TO_BANK";

export const POST_EMAIL = "POST_EMAIL";
export const EMAIL_VERIFY = "EMAIL_VERIFY";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PIN = "CHANGE_PIN";

export const GET_CREDIT_STATUS = "GET_CREDIT_STATUS";
export const GET_CREDIT_HISTORY = "GET_CREDIT_HISTORY";
export const REQUEST_CREDIT = "REQUEST_CREDIT";
