export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const NOTIFICATION_TOKEN = "NOTIFICATION_TOKEN";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const POST_PREREG_DETAILS = "POST_PREREG_DETAILS";
export const REG_AUTH_CHECKER = "REG_AUTH_CHECKER";
export const REGISTER_USER = "REGISTER_USER";

export const GET_USER_PERIODS = "GET_USER_PERIODS";
export const GET_USER_TRANSACTION = "GET_USER_TRANSACTION";
export const POST_TRANSACTION = "POST_TRANSACTION";
export const FINANCE_VISUALIZER = "FINANCE_VISUALIZER";

export const SEND_MONEY_PRE_VERIFY = "SEND_MONEY_PRE_VERIFY";
export const POST_SEND_MONEY = "POST_SEND_MONEY";

export const GET_BANK = "GET_BANK";
export const RESOLVE_BANK = "RESOLVE_BANK";
export const UPDATE_BANK = "UPDATE_BANK";
export const WITHDRAW_TO_BANK = "WITHDRAW_TO_BANK";

export const POST_EMAIL = "POST_EMAIL";
export const EMAIL_VERIFY = "EMAIL_VERIFY";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PIN = "CHANGE_PIN";

export const VERIFY_BUSINESS_UID = "VERIFY_BUSINESS_UID";
export const MOBILE_BUSINESS_LINK = "MOBILE_BUSINESS_LINK";
export const MARKETPLACE_BUSINESS = "MARKETPLACE_BUSINESS";
export const MARKETPLACE_PAY_BUSINESS = "MARKETPLACE_PAY_BUSINESS";

export const GET_TV_BOUQUETS = "GET_TV_BOUQUETS";
export const GET_BOUQUETS_ADDONS = "GET_BOUQUETS_ADDONS";
export const GET_CUSTOMER_NAME = "GET_CUSTOMER_NAME";
export const ELECTRICITY_VALIDATE = "ELECTRICITY_VALIDATE";
export const BUY_UTILITY = "BUY_UTILITY";
export const GET_DATA_BUNDLES = "GET_DATA_BUNDLES";

export const GET_BUSINESS_NOTIFICATIONS = "GET_BUSINESS_NOTIFICATIONS";

export const CARD_DEPOSIT = "CARD_DEPOSIT";

export const GET_CARDS = "GET_CARDS";
export const TOKEN_DEPOSIT = "TOKEN_DEPOSIT";

export const GET_FX_RATE = "GET_FX_RATE";
export const PUSH_ACTIVITY_VERIFICATION_TOKEN = "PUSH_ACTIVITY_VERIFICATION_TOKEN";
